name: Discover Trends

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger from GitHub UI

permissions:
  contents: read

jobs:
  discover-trends:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Trend Discovery
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${SUPABASE_URL}/functions/v1/discover-trends" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
            -H "Content-Type: application/json")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "Response: $BODY"
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "::error::Trend discovery failed with status $HTTP_CODE"
            exit 1
          fi
          
          echo "✅ Trend discovery completed successfully"
